const routes = Object.freeze({
  ACCOUNT: "Account",
  ARCHIVED: "Archived",
  ARCHIVED_LISTING_DETAILS: "archivedListingDetails",
  EDIT_USER_PROFILE: "EditUserProfile",
  FORGOT: "ForgotPassword",
  IMAGES: "Images",
  ITEMS: "items",
  LISTINGS: "Feed",
  LISTING_DETAILS: "ListingDetails",
  LISTING_EDIT_MAIN: "ListingEditMain",
  LISTING_EDIT_NEW: "ListingEditNew",
  LISTING_EDIT_REFURBISHMENT: "ListingEditRefurbishment",
  LISTING_EDIT_OPTIONS: "Options",
  LOGIN: "Login",
  MESSAGES: "Messages",
  OTB_CODE: "OTBCode",
  PROFILE: "Profile",
  REGISTER: "Register",
  RECYCLE: "recycleBin",
  RECYCLE_BIN_LISTING_DETAILS: "recycleBinDetails",
  VIEW_IMAGE: "ViewImage",
  USER_LISTINGS: "UserListings",
  USER_LISTING_DETAILS: "UserListingDetails",
  USERS: "Users",
  WELCOME: "Welcome",
});

export default routes;
