const routes = Object.freeze({
  ACCOUNT: "Account",
  ARCHIVED: "Archived",
  ARCHIVED_LISTING_DETAILS: "archivedListingDetails",
  EDIT_USER_PROFILE: "EditUserProfile",
  FORGOT: "ForgotPassword",
  IMAGES: "Images",
  ITEMS: "items",
  LISTINGS: "Feed",
  LISTING_EDIT_FINAL: "listingEditFinal",
  LISTING_DETAILS: "ListingDetails",
  LISTING_EDIT_MAIN: "ListingEditMain",
  LISTING_EDIT: "ListingEdit",
  LISTING_EDIT_OPTIONS: "EditOptions",
  LISTING_EDIT_FINAL: "EditFinal",
  LOGIN: "Login",
  MESSAGES: "Messages",
  OTB_CODE: "OTBCode",
  PROFILE: "Profile",
  REGISTER: "Register",
  RECYCLE: "recycleBin",
  RECYCLE_BIN_LISTING_DETAILS: "recycleBinDetails",
  VIEW_IMAGE: "ViewImage",
  USER_LISTINGS: "UserListings",
  USER_LISTING_DETAILS: "UserListingDetails",
  USERS: "Users",
  WELCOME: "Welcome",
  SEARCH: "Search",
  NOTIFICATION: "notification",
});

export default routes;
