import { Platform, StyleSheet } from "react-native";
import customProps from "../customProps";

const Styles = StyleSheet.create({
  colors: customProps,
  container: {
    flex: 1,
    backgroundColor: customProps.primaryColorDark,
    alignItems: "center",
    justifyContent: "space-around",
    height: "100%",
    width: "100%",
    paddingVertical: 30,
  },
  primaryImage: {
    width: "100%",
    height: "90%",
    alignSelf: "center",
    marginVertical: 10,
    marginRight: 15,
  },
  containerFlexRow: {
    width: "65%",
    transform: [{ translateY: -50 }],
    alignItems: "center",
    justifyContent: "space-between",
  },
  secondaryContainerPadding: {
    padding: 10,
    height: 75,
    justifyContent: "space-between",
  },
  containerFlexRow: {
    width: "65%",
    height: "22%",
    transform: [{ translateY: -50 }],
    alignItems: "center",
    justifyContent: "space-between",
  },
  heroImage: {
    width: "90%",
    height: 265,
    alignSelf: "center",
  },
  heroImageVertical: {
    width: "95%",
    height: 310,
    top: 30,
    alignSelf: "flex-end",
  },
  inputContinuer: {
    padding: 10,
    paddingHorizontal: 20,
    alignItems: "center",
    alignSelf: "center",
    justifyContent: "center",
    width: "95%",
  },
  OTBInputContinuer: {
    padding: 10,
    paddingHorizontal: 20,
    alignItems: "center",
    alignSelf: "center",
    justifyContent: "center",
    width: "100%",
    maxWidth: 550,
    marginVertical: 20,
  },
  OTBTextInputContinuer: {
    flexDirection: "row",
    justifyContent: "space-around",
    alignSelf: "center",
    width: "100%",
    alignItems: "center",
  },
  textInputOTB: {
    backgroundColor: customProps.darkCardBackgroundColor,
    color: customProps.primaryColorLight,
    borderColor: customProps.secondaryColor,
    fontSize: 25,
    width: 55,
    height: 55,
    marginVertical: 5,
    borderRadius: 5,
    borderWidth: 1,
    textAlign: "center",
    padding: Platform.OS === "android" ? 5 : 10,
    fontWeight: "500",
  },
  countryCodeInput: {
    alignItems: "center",
    width: "100%",
    backgroundColor: "#1E2931",
    borderColor: "#EDEEE4",
    borderRadius: 5,
    borderWidth: 1.5,
    marginVertical: 6,
    overflow: "hidden",
    flexDirection: "row",
  },
  countryCode: {
    color: customProps.secondaryColor,
    width: "100%",
    paddingHorizontal: 10,
    ...customProps.font,
    fontSize: 19,
  },
  linkText: {
    color: customProps.primaryColor,
    textTransform: "capitalize",
    ...customProps.font,
    fontWeight: "700",
    fontSize: 22,
    marginBottom: 3,
  },
  linkTextPrimary: {
    margin: 30,
    textAlign: "right",
  },
  primaryTextHeroSection: {
    color: customProps.primaryColorLight,
    fontWeight: "800",
    ...customProps.font,
    fontSize: 52.5,
    marginLeft: 25,
    transform: [{ translateY: -20 }],
  },
  containerFlexColumn: {
    transform: [{ translateY: 150 }],
    alignItems: "center",
    justifyContent: "space-around",
    height: "30%",
  },
  mainLogo: {
    width: "95%",
    height: "60%",
  },
  mainLogoHeroSection: {
    width: "90%",
    height: "50%",
  },
  ErrorMessage: {
    color: customProps.importantIconColor,
    ...customProps.font,
    fontSize: 25,
    padding: 5,
    marginBottom: 5,
    textAlign: "center",
    width: "100%",
    alignSelf: "flex-start",
  },
  primaryText: {
    ...customProps.font,
    color: customProps.primaryColor,
    fontWeight: "bold",
    fontSize: 40,
    marginTop: 20,
    textAlign: "center",
  },
  secondaryTextHeroSection: {
    ...customProps.font,
    color: customProps.primaryColorLight,
    fontWeight: "bold",
    fontSize: 35,
    padding: 10,
    textAlign: "center",
    marginVertical: 20,
  },

  secondaryText: {
    ...customProps.font,
    color: customProps.primaryColorLight,
    fontSize: 20,
    textTransform: "capitalize",
  },
  secondaryTextGray: {
    ...customProps.font,
    color: customProps.primaryColorLightGray,
    fontSize: 20,
    lineHeight: 28,
    padding: 10,
    paddingTop: 0,
    fontWeight: "500",
  },
  containerFlexRowLinks: {
    flexDirection: "row",
    alignItems: "center",
    alignSelf: "center",
    margin: 30,
    top: 20,
  },
  containerFlexRowLinksAbsolute: {
    flexDirection: "row",
    alignItems: "center",
    alignSelf: "center",
    margin: 30,
    top: 50,
  },

  innerText: {
    ...customProps.font,
    fontSize: customProps.innerTextFontSize,
  },
  innerPrimaryText: {
    color: customProps.primaryColor,
  },
  innerSecondaryText: {
    ...customProps.font,

    color: customProps.secondaryColor,
  },
  button: {
    width: "100%",
    justifyContent: "center",
    alignItems: "center",
  },
  textContainer: {
    width: "100%",
    alignItems: "center",
    justifyContent: "center",
    textAlign: "center",
    height: 250,
    padding: 5,
    margin: 15,
  },
  formField: {
    alignItems: "center",
    backgroundColor: "#1E2931",
    borderColor: "#EDEEE4",
    borderRadius: 5,
    borderWidth: 1.5,
    marginVertical: 6,
    overflow: "hidden",
    padding: 10,
  },
  ImageContainer: {
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
    borderRadius: 15,
    padding: 5,
    margin: 10,
    marginLeft: 15,
    borderRadius: 15,
    backgroundColor: customProps.darkCardBackgroundColor,
  },
  labelStyle: {
    ...customProps.font,
    textAlign: "left",
    fontSize: 25,
    color: "#EDEEE4",
    width: "100%",
    padding: 10,
  },
  primaryButton: {},
  heroImageError: {
    width: "100%",
    height: 300,
    alignSelf: "center",
  },
  errorText: {
    margin: 10,
    textAlign: "center",
    ...customProps.font,
    fontSize: 22,
    color: customProps.primaryColorLight,
    textTransform: "capitalize",
  },
  errorContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    alignSelf: "center",
    padding: 10,
    width: "95%",
    zIndex: 2,
    borderRadius: 10,
    backgroundColor: customProps.darkOpacity,
  },
});

export default Styles;
